// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CPU() {
  return window['go']['main']['App']['CPU']();
}

export function DISK() {
  return window['go']['main']['App']['DISK']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
